
const state={screen:"home",index:Number(localStorage.getItem("ef_index")||"0"),flipped:false,filter:"All 100",quiz:null,selected:null,score:Number(localStorage.getItem("ef_score")||"0"),known:JSON.parse(localStorage.getItem("ef_known")||"{}"),mistakes:JSON.parse(localStorage.getItem("ef_mistakes")||"[]")};
const cats=["All 100",...Array.from(new Set(WORDS.map(w=>w[3])))];
function save(){localStorage.setItem("ef_index",state.index);localStorage.setItem("ef_known",JSON.stringify(state.known));localStorage.setItem("ef_mistakes",JSON.stringify(state.mistakes));localStorage.setItem("ef_score",state.score)}
function list(){return state.filter=="All 100"?WORDS:WORDS.filter(w=>w[3]==state.filter)}
function W(){let arr=list();if(state.index>=arr.length)state.index=0;return arr[state.index]}
function progress(){return Math.round(Object.keys(state.known).length/WORDS.length*100)}
function speak(t,slow=false){if(!("speechSynthesis" in window)){alert("Audio is not available on this browser.");return}let u=new SpeechSynthesisUtterance(t);u.lang="fr-FR";u.rate=slow?.62:.92;speechSynthesis.cancel();speechSynthesis.speak(u)}
function setScreen(s){state.screen=s;render()}function setFilter(f){state.filter=f;state.index=0;state.flipped=false;render()}
function header(){return `<header class="header"><div class="brand"><div class="logo">🇫🇷</div><div><h1>Everyday French</h1><p class="sub">100 phrases people use in France</p></div></div><div class="badges"><span class="badge">✅ 100 practical phrases</span><span class="badge">☕ Café</span><span class="badge">🥖 Bakery</span><span class="badge">💊 Pharmacy</span></div></header>`}
function home(){let p=progress();return `<section class="screen"><div class="card hero"><p class="eyebrow">Everyday A1 French</p><h2 class="title">100 useful two-word phrases</h2><p class="desc">Made for real life in France: cafés, bakeries, supermarkets, pharmacy, doctor, neighbours, appointments and directions.</p><div class="big" style="margin-top:16px">${WORDS.length} phrases</div><div class="sound">Start with phrases you will actually hear and use.</div><button style="margin-top:14px" onclick="setScreen('sets')">View 10 daily-life sets</button><button class="secondary" style="margin-top:10px" onclick="setScreen('cards')">Start flashcards</button></div><div class="card"><p class="eyebrow">Progress</p><h2 class="title" style="font-size:23px">${p}% learned</h2><div class="progresswrap"><div class="progressbar" style="width:${p}%"></div></div><p class="small">${Object.keys(state.known).length} of ${WORDS.length} marked as known</p></div><div class="card"><p class="eyebrow">Choose category</p>${cats.map(c=>`<span onclick="setFilter('${c}')" class="chip ${state.filter==c?'active':''}">${c}</span>`).join("")}</div></section>`}
function sets(){return `<section class="screen"><div class="card hero"><p class="eyebrow">All sets</p><h2 class="title">10 everyday situations</h2><p class="desc">Each set has 10 phrases for daily life in France.</p></div>${cats.filter(c=>c!="All 100").map(c=>{let arr=WORDS.filter(w=>w[3]==c);return `<div class="setcard" onclick="setFilter('${c}');setScreen('words')"><p class="eyebrow">${c}</p><h2 class="title" style="font-size:22px">${arr.length} phrases</h2><p class="small">${arr[0][0]} · ${arr[1][0]} · ${arr[2][0]}</p></div>`}).join("")}<button class="secondary" onclick="setFilter('All 100');setScreen('words')">Show full list of 100</button></section>`}
function words(){let arr=list();return `<section class="screen"><div class="card"><p class="eyebrow">Phrase list</p><h2 class="title">${state.filter}</h2><p class="desc">${arr.length} phrases shown.</p></div>${arr.map((w,i)=>`<div class="wordrow"><div class="num">${i+1}</div><div><div class="fr">${w[0]}</div><div class="en">${w[1]} · ${w[2]}</div></div><div class="cat">${w[3].split(" ")[0]}</div></div>`).join("")}</section>`}
function cards(){let w=W(),arr=list();return `<section class="screen"><div class="card"><p class="eyebrow">Flashcard</p><h2 class="title">${state.filter}</h2><p class="desc">Card ${state.index+1} of ${arr.length}</p></div><div class="flash" onclick="state.flipped=!state.flipped;render()">${state.flipped?`<div><p class="eyebrow">French</p><div class="big">${w[0]}</div><p>${w[1]}</p><div class="sound">${w[2]}</div></div>`:`<div><p class="eyebrow">English</p><div class="big">${w[1]}</div><p class="flashsmall">Tap to reveal French</p></div>`}</div><div class="grid2" style="margin-top:14px"><button class="secondary" onclick="prev()">Previous</button><button onclick="next()">Next</button></div><div class="grid2" style="margin-top:10px"><button class="secondary" onclick="speak(\`${w[0]}\`,true)">Slow audio</button><button class="secondary" onclick="speak(\`${w[0]}\`,false)">Normal audio</button></div><button style="margin-top:10px" onclick="known()">I know this phrase</button></section>`}
function next(){state.index=(state.index+1)%list().length;state.flipped=false;save();render()}function prev(){state.index=Math.max(0,state.index-1);state.flipped=false;save();render()}function known(){state.known[W()[0]]=true;save();next()}
function practice(){return `<section class="screen"><div class="card hero"><p class="eyebrow">Daily practice</p><h2 class="title">Use 5 today</h2><p class="desc">Pick 5 phrases and try to use them in real life today.</p></div><div class="card"><p class="eyebrow">Easy first phrases</p>${["Bonjour Madame","Merci beaucoup","Par carte","C’est combien","Bonne journée"].map((p,i)=>{let w=WORDS.find(x=>x[0]==p);return `<div class="wordrow"><div class="num">${i+1}</div><div><div class="fr">${w[0]}</div><div class="en">${w[1]} · ${w[2]}</div></div></div>`}).join("")}<button onclick="newQuiz();setScreen('quiz')">Start quiz</button></div></section>`}
function newQuiz(){let correct=WORDS[Math.floor(Math.random()*WORDS.length)];let opts=[correct[1]];while(opts.length<4){let x=WORDS[Math.floor(Math.random()*WORDS.length)][1];if(!opts.includes(x))opts.push(x)}opts=opts.sort(()=>Math.random()-.5);state.quiz={fr:correct[0],answer:correct[1],opts};state.selected=null}
function quiz(){if(!state.quiz)newQuiz();let q=state.quiz;return `<section class="screen"><div class="card"><p class="eyebrow">Quiz</p><h2 class="title" style="font-size:24px">What does this mean?</h2><div class="big" style="font-size:30px;margin-top:12px">${q.fr}</div></div><div class="card">${q.opts.map(o=>{let cls="option";if(state.selected){if(o==q.answer)cls+=" correct";if(o==state.selected&&o!=q.answer)cls+=" wrong"}return `<button class="${cls}" onclick="answer(\`${o}\`)">${o}</button>`}).join("")}${state.selected?`<div class="feedback ${state.selected==q.answer?'good':'bad'}">${state.selected==q.answer?'Correct!':'Not yet. Correct: '+q.answer}</div><button onclick="newQuiz();render()">Next question</button>`:""}</div></section>`}
function answer(o){if(state.selected)return;state.selected=o;if(o==state.quiz.answer){state.score++}else{state.mistakes.push({fr:state.quiz.fr,correct:state.quiz.answer,chosen:o})}save();render()}
function progressScreen(){let p=progress();return `<section class="screen"><div class="card hero"><p class="eyebrow">Progress tracker</p><h2 class="title">${p}% learned</h2><div class="progresswrap"><div class="progressbar" style="width:${p}%"></div></div></div><div class="grid2"><div class="card"><p class="eyebrow">Known</p><div class="big" style="font-size:32px">${Object.keys(state.known).length}/100</div></div><div class="card"><p class="eyebrow">Quiz score</p><div class="big" style="font-size:32px">${state.score}</div></div></div><div class="card"><p class="eyebrow">Recent mistakes</p>${state.mistakes.length?state.mistakes.slice(-8).map(m=>`<div class="wordrow"><div class="num">!</div><div><div class="fr">${m.fr}</div><div class="en">Correct: ${m.correct}</div></div></div>`).join(""):`<p class="desc">No mistakes yet.</p>`}</div><button class="secondary" onclick="reset()">Reset progress</button></section>`}
function reset(){localStorage.removeItem("ef_index");localStorage.removeItem("ef_known");localStorage.removeItem("ef_mistakes");localStorage.removeItem("ef_score");location.reload()}
function nav(){return `<nav class="nav">${[["home","🏠","Home"],["sets","🔟","Sets"],["words","📋","100"],["cards","🔁","Cards"],["progress","🏆","Progress"]].map(x=>`<button class="${state.screen==x[0]?'active':''}" onclick="setScreen('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join("")}</nav>`}
function render(){let html=header();if(state.screen=="home")html+=home();if(state.screen=="sets")html+=sets();if(state.screen=="words")html+=words();if(state.screen=="cards")html+=cards();if(state.screen=="practice")html+=practice();if(state.screen=="quiz")html+=quiz();if(state.screen=="progress")html+=progressScreen();document.getElementById("app").innerHTML=`<div class="app">${html}</div>${nav()}`}
render();
