
const state={screen:"home",index:Number(localStorage.getItem("w_index")||"0"),flipped:false,filter:"All",quizIndex:0,selected:null,score:0,known:JSON.parse(localStorage.getItem("w_known")||"{}"),mistakes:JSON.parse(localStorage.getItem("w_mistakes")||"[]")};
const cats=["All",...Array.from(new Set(WORDS.map(w=>w[3])))];
function save(){localStorage.setItem("w_index",state.index);localStorage.setItem("w_known",JSON.stringify(state.known));localStorage.setItem("w_mistakes",JSON.stringify(state.mistakes))}
function list(){return state.filter=="All"?WORDS:WORDS.filter(w=>w[3]==state.filter)}
function W(){let arr=list(); if(state.index>=arr.length)state.index=0; return arr[state.index]}
function progress(){return Math.round(Object.keys(state.known).length/WORDS.length*100)}
function speak(t,slow=false){if(!("speechSynthesis" in window)){alert("Audio not available in this browser.");return}let u=new SpeechSynthesisUtterance(t);u.lang="fr-FR";u.rate=slow?.62:.92;speechSynthesis.cancel();speechSynthesis.speak(u)}
function setScreen(s){state.screen=s;render()} function setFilter(f){state.filter=f;state.index=0;state.flipped=false;render()}
function header(){return `<header class="header"><div class="brand"><div class="logo">💬</div><div><h1>Bonjour Zahara</h1><p class="sub">100 A1 two-word French phrases</p></div></div><div class="badges"><span class="badge">🎯 A1 Beginner</span><span class="badge">📍 Real life France</span><span class="badge">🔁 Flashcards</span></div></header>`}
function home(){let p=progress();return `<section class="screen"><div class="card hero"><p class="eyebrow">Beginner A1</p><h2 class="title">100 two-word French phrases</h2><p class="desc">Learn small useful phrases first, so you can recognise French faster in shops, cafés, appointments, phone calls and daily life.</p><div class="big" style="margin-top:16px">${W()[0]}</div><p>${W()[1]}</p><div class="sound">${W()[2]}</div><button style="margin-top:14px" onclick="setScreen('cards')">Start flashcards</button></div><div class="card"><p class="eyebrow">Progress</p><h2 class="title" style="font-size:23px">${p}% learned</h2><div class="progresswrap"><div class="progressbar" style="width:${p}%"></div></div><p class="small">${Object.keys(state.known).length} of ${WORDS.length} marked as known</p></div><div class="card"><p class="eyebrow">Categories</p>${cats.map(c=>`<span onclick="setFilter('${c}')" class="chip ${state.filter==c?'active':''}">${c}</span>`).join("")}</div></section>`}
function words(){let arr=list();return `<section class="screen"><div class="card"><p class="eyebrow">Word list</p><h2 class="title">${state.filter} phrases</h2><p class="desc">${arr.length} phrases in this section.</p></div>${arr.map((w,i)=>`<div class="wordrow"><div class="num">${i+1}</div><div><div class="fr">${w[0]}</div><div class="en">${w[1]} · ${w[2]}</div></div><div class="cat">${w[3]}</div></div>`).join("")}</section>`}
function cards(){let w=W(), arr=list();return `<section class="screen"><div class="card"><p class="eyebrow">Flashcard</p><h2 class="title">${state.filter}</h2><p class="desc">Card ${state.index+1} of ${arr.length}</p></div><div class="flash" onclick="state.flipped=!state.flipped;render()">${state.flipped?`<div><p class="eyebrow">French</p><div class="big">${w[0]}</div><p>${w[1]}</p><div class="sound">${w[2]}</div></div>`:`<div><p class="eyebrow">English</p><div class="big">${w[1]}</div><p class="flashsmall">Tap to reveal French</p></div>`}</div><div class="grid2" style="margin-top:14px"><button class="secondary" onclick="prev()">Previous</button><button onclick="next()">Next</button></div><div class="grid2" style="margin-top:10px"><button class="secondary" onclick="speak('${w[0].replaceAll("'","\\'")}',true)">Slow audio</button><button class="secondary" onclick="speak('${w[0].replaceAll("'","\\'")}',false)">Normal audio</button></div><button style="margin-top:10px" onclick="known()">I know this phrase</button></section>`}
function next(){state.index=(state.index+1)%list().length;state.flipped=false;save();render()} function prev(){state.index=Math.max(0,state.index-1);state.flipped=false;save();render()}
function known(){state.known[W()[0]]=true;save();next()}
function practice(){return `<section class="screen"><div class="card hero"><p class="eyebrow">Daily practice</p><h2 class="title">5-minute routine</h2><p class="desc">Do this every morning or before going to a café/shop.</p></div><div class="card"><ol><li>Read 10 cards.</li><li>Listen slowly to each phrase.</li><li>Repeat each phrase 3 times.</li><li>Mark only easy phrases as known.</li><li>Quiz yourself.</li></ol></div><div class="card"><p class="eyebrow">Speaking challenge</p><h2 class="title" style="font-size:23px">Use 3 phrases today</h2><p>Bonjour Madame</p><p>Merci beaucoup</p><p>Par carte</p><button onclick="setScreen('quiz')">Start quiz</button></div></section>`}
function makeQuiz(){let correct=WORDS[Math.floor(Math.random()*WORDS.length)];let opts=[correct[1]];while(opts.length<4){let x=WORDS[Math.floor(Math.random()*WORDS.length)][1];if(!opts.includes(x))opts.push(x)}opts=opts.sort(()=>Math.random()-.5);return {fr:correct[0],answer:correct[1],opts}}
let currentQuiz=makeQuiz();
function quiz(){return `<section class="screen"><div class="card"><p class="eyebrow">Quiz</p><h2 class="title" style="font-size:24px">What does this mean?</h2><div class="big" style="font-size:30px;margin-top:12px">${currentQuiz.fr}</div></div><div class="card">${currentQuiz.opts.map(o=>{let cls="option";if(state.selected){if(o==currentQuiz.answer)cls+=" correct";if(o==state.selected&&o!=currentQuiz.answer)cls+=" wrong"}return `<button class="${cls}" onclick="answer('${o.replaceAll("'","\\'")}')">${o}</button>`}).join("")}${state.selected?`<div class="feedback ${state.selected==currentQuiz.answer?'good':'bad'}">${state.selected==currentQuiz.answer?'Correct!':'Not yet. Correct: '+currentQuiz.answer}</div><button onclick="nextQuiz()">Next question</button>`:""}</div></section>`}
function answer(o){if(state.selected)return;state.selected=o;if(o==currentQuiz.answer)state.score++;else state.mistakes.push({fr:currentQuiz.fr,correct:currentQuiz.answer,chosen:o});save();render()} function nextQuiz(){state.selected=null;currentQuiz=makeQuiz();render()}
function progressScreen(){let p=progress();return `<section class="screen"><div class="card hero"><p class="eyebrow">Progress tracker</p><h2 class="title">${p}% learned</h2><div class="progresswrap"><div class="progressbar" style="width:${p}%"></div></div></div><div class="grid2"><div class="card"><p class="eyebrow">Known</p><div class="big" style="font-size:32px">${Object.keys(state.known).length}</div></div><div class="card"><p class="eyebrow">Mistakes</p><div class="big" style="font-size:32px">${state.mistakes.length}</div></div></div><div class="card"><p class="eyebrow">Recent mistakes</p>${state.mistakes.length?state.mistakes.slice(-8).map(m=>`<div class="wordrow"><div class="num">!</div><div><div class="fr">${m.fr}</div><div class="en">Correct: ${m.correct}</div></div></div>`).join(""):`<p class="desc">No mistakes yet.</p>`}</div><button class="secondary" onclick="reset()">Reset progress</button></section>`}
function reset(){localStorage.removeItem("w_index");localStorage.removeItem("w_known");localStorage.removeItem("w_mistakes");location.reload()}
function nav(){return `<nav class="nav">${[["home","🏠","Home"],["words","📋","Words"],["cards","🔁","Cards"],["practice","🗣️","Practice"],["progress","🏆","Progress"]].map(x=>`<button class="${state.screen==x[0]?'active':''}" onclick="setScreen('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join("")}</nav>`}
function render(){let html=header();if(state.screen=="home")html+=home();if(state.screen=="words")html+=words();if(state.screen=="cards")html+=cards();if(state.screen=="practice")html+=practice();if(state.screen=="quiz")html+=quiz();if(state.screen=="progress")html+=progressScreen();document.getElementById("app").innerHTML=`<div class="app">${html}</div>${nav()}`}
render();
